kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: pvc-webhook
  annotations:
    cert-manager.io/inject-ca-from: cluster-tools/pvc-webhook
webhooks:
  - name: pvc-webhook.cluster-tools.svc
    clientConfig:
      service:
        namespace: cluster-tools
        name: pvc-webhook
        path: /validate
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - "v1"
        resources:
          - "persistentvolumeclaims"
        operations:
          - "CREATE"
          - "UPDATE"
        scope: Namespaced
    sideEffects: None
    admissionReviewVersions:
      - "v1"